<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DataSources\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pidss.Platform.Application\Pidss.Platform.Application.csproj" />
    <ProjectReference Include="..\Pidss.Platform.Domain\Pidss.Platform.Domain.csproj" />
  </ItemGroup>

</Project>
