<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pidss.Platform.Application\Pidss.Platform.Application.csproj" />
    <ProjectReference Include="..\Pidss.Platform.Infrastructure\Pidss.Platform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
